### ISSUE TITLE
в package.json битые пути (../)

### ISSUE THREAD

**Issue by bobagold** [Grenguar/translit-telegram-bot#1]

**Comment by bobagold** [comment]
в названии функции transliterateComplcatedRussianLetters опечатка
в теле функции много копипасты

**Comment by Grenguar** [comment]
@bobagold спасибо за комментарии, очень ценно!

не придумал как сделать без копипасты.
битые пути в main и directories?

**Comment by bobagold** [comment]
@Grenguar без копипасты будет что-то типо
`return Object.keys(dictionary).filter((key) => key.length > 1).reduce((memo, key) => memo.replace(new RegExp(key, 'g'), dictionary[key]), word);` только Shch и Sh надо местами поменять в json

**Comment by bobagold** [comment]
@Grenguar про битые пути верно, main и directories

**Comment by bobagold** [comment]
https://david-dm.org/Grenguar/translit-telegram-bot.svg
